// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Form() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"w-full flex flex-col justify-start items-start\"><div class=\"header flex items-center justify-start\"><div class=\"icon w-10 h-10 rounded-full flex grid place-items-center bg-yellow-500 mr-4\"><i class=\"fa fa-bolt\" aria-hidden=\"true\"></i></div><div class=\"title uppercase font-bold text-xl tracking-widest opacity-50\">bolt</div></div><div class=\"separator my-8\"></div><div class=\"welcome-text\"><p class=\"text-2xl font-bold opacity-80\">Welcome back!</p><small class=\"text-gray-400 font-bold\">Please login to your account</small></div><div class=\"separator my-4\"></div><div class=\"form w-full\"><form class=\"w-full flex flex-col justify-between items-start\"><div class=\"input-group flex flex-col items-start justify-start w-full\"><label for=\"username\" class=\"font-bold my-2 opacity-80\">Username/Email Address</label> <input type=\"text\" name=\"username\" placeholder=\"you@example.com\" class=\"w-full py-2 px-6 border rounded-sm\"></div><div class=\"separator my-2\"></div><div class=\"input-group flex flex-col items-start justify-start w-full\"><label for=\"password\" class=\"font-bold my-2 opacity-80\">Password</label> <input type=\"password\" name=\"password\" placeholder=\"******\" class=\"w-full py-2 px-6 border rounded-sm\"></div><div class=\"separator my-2\"></div><div class=\"input-group flex items-start justify-between w-full\"><div class=\"flex justify-start items-center\"><input type=\"radio\" name=\"remember-me\"> <label for=\"remember-me\" class=\"mx-2 my-2 opacity-40\">Remember me</label></div><div class=\"font-semibold font-xs opacity-60\">Forgot password?</div></div><div class=\"separator my-2\"></div><div class=\"input-group flex items-center justify-center w-full bg-[#101415] text-yellow-500 py-3\"><span class=\"mr-4\">Login to Bolt!</span> <span><i class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></i></span></div></form></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
